name: Publish NuGet Package
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkgs
    
    - name: Push to GitHub Packages
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" \
          --source https://nuget.pkg.github.com/taviovieira89/index.json \
          --api-key ${{ secrets.TOOLKIT_AUTH_TOKEN }} \
          --skip-duplicate
